import { describe, expect, it, vi } from "vitest";
import { useMainAppLayoutSurfaces } from "./useMainAppLayoutSurfaces";

function buildArgs(
  review: boolean,
  fileTreeAvailable = true,
): Parameters<typeof useMainAppLayoutSurfaces>[0] {
  return {
    appSettings: {
      usageShowRemaining: false,
      composerCodeBlockCopyUseModifier: false,
      showMessageFilePath: false,
      openAppTargets: [],
      selectedOpenAppId: "vscode",
      experimentalAppsEnabled: false,
      followUpMessageBehavior: "queue",
      composerFollowUpHintEnabled: false,
      dictationEnabled: false,
      splitChatDiffView: false,
      gitDiffIgnoreWhitespaceChanges: false,
    },
    workspaces: [],
    groupedWorkspaces: [],
    workspaceGroupsCount: 0,
    deletingWorktreeIds: new Set<string>(),
    newAgentDraftWorkspaceId: null,
    startingDraftThreadWorkspaceId: null,
    threadsByWorkspace: {},
    threadParentById: {},
    threadStatusById: {},
    threadResumeLoadingById: {},
    threadListLoadingByWorkspace: {},
    threadListPagingByWorkspace: {},
    threadListCursorByWorkspace: {},
    pinnedThreadsVersion: 0,
    threadListSortKey: "updated_at",
    onSetThreadListSortKey: vi.fn(),
    threadListOrganizeMode: "by_project",
    onSetThreadListOrganizeMode: vi.fn(),
    onRefreshAllThreads: vi.fn(),
    activeWorkspace: {
      id: "ws-1",
      name: "Workspace",
      path: "/tmp/workspace",
      connected: true,
      kind: "main",
      settings: { sidebarCollapsed: false },
    },
    activeWorkspaceId: "ws-1",
    activeThreadId: null,
    activeItems: [],
    userInputRequests: [],
    approvals: [],
    activeRateLimits: null,
    activeAccount: null,
    homeRateLimits: null,
    homeAccount: null,
    accountSwitching: false,
    onSwitchAccount: vi.fn(),
    onCancelSwitchAccount: vi.fn(),
    onDecision: vi.fn(),
    onRemember: vi.fn(),
    onUserInputSubmit: vi.fn(),
    onPlanAccept: vi.fn(),
    onPlanSubmitChanges: vi.fn(),
    activePlan: null,
    activeTokenUsage: null,
    latestAgentRuns: [],
    isLoadingLatestAgents: false,
    usageSnapshotAvailable: true,
    localUsageSnapshot: null,
    isLoadingLocalUsage: false,
    localUsageError: null,
    onRefreshLocalUsage: vi.fn(),
    usageMetric: "tokens",
    onUsageMetricChange: vi.fn(),
    usageWorkspaceId: null,
    usageWorkspaceOptions: [],
    onUsageWorkspaceChange: vi.fn(),
    gitState: {
      gitPanelMode: "diff",
      handleGitPanelModeChange: vi.fn(),
      filePanelMode: "git",
      setFilePanelMode: vi.fn(),
      activeParentWorkspace: null,
      worktreeApplyLoading: false,
      worktreeApplyError: null,
      worktreeApplySuccess: false,
      handleApplyWorktreeChanges: vi.fn(),
      gitStatus: {
        branchName: "main",
        totalAdditions: 0,
        totalDeletions: 0,
        error: null,
        stagedFiles: [],
        unstagedFiles: [{ path: "src/file.ts", status: "M", additions: 1, deletions: 0 }],
      },
      fileStatus: "1 file changed",
      perFileDiffGroups: [],
      gitLogError: null,
      gitLogLoading: false,
      handleSelectPerFileDiff: vi.fn(),
      handleSelectDiff: vi.fn(),
      gitLogEntries: [],
      gitLogTotal: 0,
      gitLogAhead: 0,
      gitLogBehind: 0,
      gitLogAheadEntries: [],
      gitLogBehindEntries: [],
      gitLogUpstream: null,
      selectedCommitSha: null,
      handleSelectCommit: vi.fn(),
      gitIssues: [],
      gitIssuesTotal: 0,
      gitIssuesLoading: false,
      gitIssuesError: null,
      gitPullRequests: [],
      gitPullRequestsTotal: 0,
      gitPullRequestsLoading: false,
      gitPullRequestsError: null,
      selectedPullRequest: null,
      setSelectedCommitSha: vi.fn(),
      gitRemoteUrl: null,
      activeGitRoot: null,
      gitRootCandidates: [],
      gitRootScanDepth: 3,
      gitRootScanLoading: false,
      gitRootScanError: null,
      gitRootScanHasScanned: false,
      activeDiffs: [],
      centerMode: "chat",
      selectedDiffPath: null,
      setCenterMode: vi.fn(),
      setSelectedDiffPath: vi.fn(),
      setGitRootScanDepth: vi.fn(),
      scanGitRoots: vi.fn(),
      handleSetGitRoot: vi.fn(),
      handlePickGitRoot: vi.fn(),
      initGitRepoLoading: false,
      handleStageGitAll: vi.fn(),
      handleStageGitFile: vi.fn(),
      handleUnstageGitFile: vi.fn(),
      handleRevertGitFile: vi.fn(),
      handleRevertAllGitChanges: vi.fn(),
      commitMessage: "",
      commitMessageLoading: false,
      commitMessageError: null,
      handleCommitMessageChange: vi.fn(),
      handleGenerateCommitMessage: vi.fn(),
      handleCommit: vi.fn(),
      handleCommitAndPush: vi.fn(),
      handleCommitAndSync: vi.fn(),
      handlePull: vi.fn(),
      handleFetch: vi.fn(),
      handlePush: vi.fn(),
      handleSync: vi.fn(),
    },
    composerWorkspaceState: {
      commandCapabilities: {
        fork: true,
        compact: true,
        review,
        mcp: true,
      },
      steerAvailable: false,
      fileTreeAvailable,
    },
    promptActions: {
      reviewActive: false,
      reviewMode: null,
      reviewBranchOptions: [],
      reviewCommitOptions: [],
      reviewCanConfirmBranch: false,
      reviewCanConfirmCommit: false,
      reviewIsBranchStep: false,
      reviewIsCommitStep: false,
      reviewIsCustomStep: false,
    },
    worktreeState: {
      activeParentWorkspace: null,
      isWorktreeWorkspace: false,
    },
    sidebarHandlers: {
      handleSelectWorkspace: vi.fn(),
      handleToggleWorkspaceExpanded: vi.fn(),
      handleRenameWorkspace: vi.fn(),
      handleDeleteWorkspace: vi.fn(),
      handleOpenWorkspaceFolder: vi.fn(),
      handleOpenWorkspaceSettings: vi.fn(),
      handleDuplicateWorkspace: vi.fn(),
      handleToggleWorkspaceFavorite: vi.fn(),
      handleDisconnectWorkspace: vi.fn(),
    },
    displayNodes: {
      primaryNodes: [],
      gitNodes: [],
      secondaryNodes: [],
    },
    threadPinning: {
      pinThread: vi.fn(),
      unpinThread: vi.fn(),
      isThreadPinned: vi.fn(() => false),
      getPinTimestamp: vi.fn(() => null),
      getThreadArgsBadge: vi.fn(() => null),
    },
    workspaceDrop: {
      workspaceDropTargetRef: { current: null },
      isWorkspaceDropActive: false,
      workspaceDropText: null,
      onWorkspaceDragOver: vi.fn(),
      onWorkspaceDragEnter: vi.fn(),
      onWorkspaceDragLeave: vi.fn(),
      onWorkspaceDrop: vi.fn(),
    },
    threadNavigation: {
      exitDiffView: vi.fn(),
      clearDraftState: vi.fn(),
      selectWorkspace: vi.fn(),
      setActiveThreadId: vi.fn(),
      resetPullRequestSelection: vi.fn(),
      selectHome: vi.fn(),
    },
    pullRequestComposer: {
      composerSendLabel: null,
      handleSelectPullRequest: vi.fn(),
    },
    dictationUi: {
      onOpenDictationSettings: vi.fn(),
      dictationTranscript: "",
      dictationError: null,
      dictationHint: null,
    },
    openAppIconById: {},
    openInitGitRepoPrompt: vi.fn(),
    startUncommittedReview: vi.fn(),
    handleAddWorkspace: vi.fn(),
    openWorkspaceFromUrlPrompt: vi.fn(),
    handleAddAgent: vi.fn(),
    handleAddWorktreeAgent: vi.fn(),
    handleAddCloneAgent: vi.fn(),
    handleOpenThreadLink: vi.fn(),
    handleSelectOpenAppId: vi.fn(),
    handleCopyThread: vi.fn(),
    handleToggleTerminalWithFocus: vi.fn(),
    launchScriptState: {
      launchScript: null,
      editorOpen: false,
      draftScript: "",
      isSaving: false,
      error: null,
      onRunLaunchScript: vi.fn(),
      onOpenEditor: vi.fn(),
      onCloseEditor: vi.fn(),
      onDraftScriptChange: vi.fn(),
      onSaveLaunchScript: vi.fn(),
    },
    launchScriptsState: undefined,
    models: [],
    selectedModelId: null,
    onSelectModel: vi.fn(),
    collaborationModes: [],
    selectedCollaborationModeId: null,
    onSelectCollaborationMode: vi.fn(),
    reasoningOptions: [],
    selectedEffort: null,
    onSelectEffort: vi.fn(),
    selectedServiceTier: null,
    reasoningSupported: false,
    codexArgsOptions: [],
    selectedCodexArgsOverride: null,
    onSelectCodexArgsOverride: vi.fn(),
    accessMode: "workspace-write",
    onSelectAccessMode: vi.fn(),
    skills: [],
    apps: [],
    prompts: [],
    composerInputRef: { current: null },
    composerEditorSettings: {
      fontSize: 14,
      lineHeight: 1.5,
      tabSize: 2,
      softWrap: true,
    },
    composerEditorExpanded: false,
    onToggleComposerEditorExpanded: vi.fn(),
    dictationReady: false,
    dictationState: "idle",
    dictationLevel: 0,
    onToggleDictation: vi.fn(),
    onCancelDictation: undefined,
    clearDictationTranscript: vi.fn(),
    clearDictationError: vi.fn(),
    clearDictationHint: vi.fn(),
    composerContextActions: [],
    reviewPrompt: null,
    closeReviewPrompt: vi.fn(),
    showPresetStep: vi.fn(),
    choosePreset: vi.fn(),
    highlightedPresetIndex: 0,
    setHighlightedPresetIndex: vi.fn(),
    highlightedBranchIndex: 0,
    setHighlightedBranchIndex: vi.fn(),
    highlightedCommitIndex: 0,
    setHighlightedCommitIndex: vi.fn(),
    handleReviewPromptKeyDown: vi.fn(),
    selectBranch: vi.fn(),
    selectBranchAtIndex: vi.fn(),
    confirmBranch: vi.fn(),
    selectCommit: vi.fn(),
    selectCommitAtIndex: vi.fn(),
    confirmCommit: vi.fn(),
    updateCustomInstructions: vi.fn(),
    confirmCustom: vi.fn(),
    handleComposerSendWithDraftStart: vi.fn(),
    interruptTurn: vi.fn(),
    terminalOpen: false,
    debugOpen: false,
    debugEntries: [],
    terminalTabs: [],
    activeTerminalId: null,
    onSelectTerminal: vi.fn(),
    onNewTerminal: vi.fn(),
    onCloseTerminal: vi.fn(),
    terminalState: "closed",
    onClearDebug: vi.fn(),
    onCopyDebug: vi.fn(),
    onResizeDebug: vi.fn(),
    onResizeTerminal: vi.fn(),
    isCompact: false,
    isPhone: false,
    activeTab: "codex",
    setActiveTab: vi.fn(),
    tabletTab: "codex",
    showMobilePollingFetchStatus: false,
    appModalsAboutOpen: false,
    updaterState: { kind: "idle" },
    startUpdate: vi.fn(),
    dismissUpdate: vi.fn(),
    postUpdateNotice: null,
    dismissPostUpdateNotice: vi.fn(),
    errorToasts: [],
    dismissErrorToast: vi.fn(),
    showDebugButton: false,
    handleDebugClick: vi.fn(),
    sidebarRateLimits: null,
    sidebarAccount: null,
  } as unknown as Parameters<typeof useMainAppLayoutSurfaces>[0];
}

describe("useMainAppLayoutSurfaces", () => {
  it("omits the git review entry point when review capability is unavailable", () => {
    const surfaces = useMainAppLayoutSurfaces(buildArgs(false));

    expect(surfaces.git.gitDiffPanelProps.onReviewUncommittedChanges).toBeUndefined();
  });

  it("wires the git review entry point and falls back to the active workspace id", () => {
    const args = buildArgs(true);

    const surfaces = useMainAppLayoutSurfaces(args);

    expect(surfaces.git.gitDiffPanelProps.onReviewUncommittedChanges).toBeDefined();

    surfaces.git.gitDiffPanelProps.onReviewUncommittedChanges?.(undefined);

    expect(args.startUncommittedReview).toHaveBeenCalledTimes(1);
    expect(args.startUncommittedReview).toHaveBeenCalledWith("ws-1");
  });

  it("passes a hidden files-tab flag when runtime file support is unavailable", () => {
    const surfaces = useMainAppLayoutSurfaces(buildArgs(true, false));

    expect((surfaces.git.gitDiffPanelProps as { showFilesTab?: boolean }).showFilesTab).toBe(
      false,
    );
  });

  it("falls back to the Git panel when files mode is selected but unsupported", () => {
    const args = buildArgs(true, false);
    args.gitState.filePanelMode = "files";

    const surfaces = useMainAppLayoutSurfaces(args);

    expect(surfaces.git.filePanelMode).toBe("git");
    expect(surfaces.git.gitDiffPanelProps.filePanelMode).toBe("git");
  });
});
